apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"creationTimestamp":"2019-12-04T06:33:55Z","generation":183,"labels":{"app.kubernetes.io/instance":"ops","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"openldap","helm.sh/chart":"openldap","release":"ops"},"name":"ops-openldap","namespace":"noi16","resourceVersion":"11585245","selfLink":"/apis/apps/v1/namespaces/noi16/statefulsets/ops-openldap","uid":"0b952691-1660-11ea-bc6c-0016ac102868"},"spec":{"podManagementPolicy":"OrderedReady","replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/instance":"ops","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"openldap","helm.sh/chart":"openldap","release":"ops"}},"serviceName":"ops-ldapservice","template":{"metadata":{"annotations":{"productID":"4DBA2B5A269740CAAE5FECDAFE0568AA","productName":"IBM Netcool Operations Insight v1.6.0.1 on IBM Cloud private","productVersion":"1.6.0.1"},"creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"ops","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"openldap","helm.sh/chart":"openldap","release":"ops"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64"]}]}]}}},"containers":[{"command":["sh","-c","curl -H \"Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN\" -H 'Accept: application/vnd.github.v3.raw' \\\n     -O -kL $GIT_MASTER_PREFIX/openldap/custom_sso.ldif\ncurl -H \"Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN\" -H 'Accept: application/vnd.github.v3.raw' \\\n     -O -kL $GIT_MASTER_PREFIX/openldap/custom_start_server\ncurl -H \"Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN\" -H 'Accept: application/vnd.github.v3.raw' \\\n     -O -kL $GIT_MASTER_PREFIX/openldap/custom_slapd.conf\ncurl -H \"Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN\" -H 'Accept: application/vnd.github.v3.raw' \\\n     -O -kL $GIT_MASTER_PREFIX/openldap/openldap-servers-2.4.44-21.el7_6.x86_64.rpm\ncurl -H \"Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN\" -H 'Accept: application/vnd.github.v3.raw' \\\n     -O -kL $GIT_MASTER_PREFIX/openldap/systemd-sysv-219-67.el7_7.1.x86_64.rpm\ncurl -H \"Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN\" -H 'Accept: application/vnd.github.v3.raw' \\\n     -O -kL $GIT_MASTER_PREFIX/openldap/tcp_wrappers-libs-7.6-77.el7.x86_64.rpm\ncurl -H \"Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN\" -H 'Accept: application/vnd.github.v3.raw' \\\n     -O -kL $GIT_MASTER_PREFIX/openldap/systemd-219-67.el7_7.1.x86_64.rpm\ncurl -H \"Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN\" -H 'Accept: application/vnd.github.v3.raw' \\\n     -O -kL $GIT_MASTER_PREFIX/openldap/systemd-libs-219-67.el7_7.1.x86_64.rpm\nsudo yum install -y systemd-sysv-219-67.el7_7.1.x86_64.rpm tcp_wrappers-libs-7.6-77.el7.x86_64.rpm\nsudo yum install -y openldap-servers-2.4.44-21.el7_6.x86_64.rpm\nsudo curl -H \"Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN\" -H 'Accept: application/vnd.github.v3.raw' \\\n     -O -kL $GIT_MASTER_PREFIX/openldap/openldaplib.tgz\nsudo tar xzvf openldaplib.tgz -C /usr/local/lib --no-same-owner\nchmod a+x custom_start_server\n/home/openldap/custom_start_server\n#/home/openldap/start_server\n#while true; do sleep 100; done\n"],"env":[{"name":"GIT_MASTER_PREFIX","valueFrom":{"configMapKeyRef":{"key":"openldapgit-master-prefix","name":"ops-openldapgit-config"}}},{"name":"LICENSE","value":"accept"},{"name":"LDAP_URL","value":"ldap://localhost:389"},{"name":"LDAP_SUFFIX","value":"dc=mycluster,dc=icp"},{"name":"LDAP_BIND_DN","value":"cn=admin,dc=mycluster,dc=icp"},{"name":"GIT_PROJECT_OPENLDAP_AUTH_TOKEN","valueFrom":{"secretKeyRef":{"key":"GIT_PROJECT_OPENLDAP_AUTH_TOKEN","name":"ops-openldap-git-secret","optional":false}}},{"name":"LDAP_BIND_PWD","valueFrom":{"secretKeyRef":{"key":"LDAP_BIND_PASSWORD","name":"ops-ldap-secret","optional":false}}},{"name":"UNITY_ADMIN_PWD","valueFrom":{"secretKeyRef":{"key":"UNITY_ADMIN_PASSWORD","name":"ops-la-secret","optional":false}}},{"name":"ICP_ADMIN_PWD","valueFrom":{"secretKeyRef":{"key":"ICP_ADMIN_PASSWORD","name":"ops-icpadmin-secret","optional":false}}},{"name":"IMPACT_ADMIN_PWD","valueFrom":{"secretKeyRef":{"key":"IMPACT_ADMIN_PASSWORD","name":"ops-impact-secret","optional":false}}},{"name":"OMNIBUS_ROOT_PWD","valueFrom":{"secretKeyRef":{"key":"OMNIBUS_ROOT_PASSWORD","name":"ops-omni-secret","optional":false}}}],"image":"mycluster.icp:8500/noi16/netcool-ldap-proxy-ee:1.6.0.1-99","imagePullPolicy":"Always","livenessProbe":{"exec":{"command":["/usr/local/bin/ldapsearch","-x","-h","localhost","-LLL","-s","base","-b","","supportedSASLMechanisms"]},"failureThreshold":3,"initialDelaySeconds":60,"periodSeconds":60,"successThreshold":1,"timeoutSeconds":1},"name":"openldap","ports":[{"containerPort":389,"protocol":"TCP"},{"containerPort":636,"protocol":"TCP"}],"readinessProbe":{"exec":{"command":["/usr/local/bin/ldapsearch","-x","-h","localhost","-LLL","-s","base","-b","","supportedSASLMechanisms"]},"failureThreshold":1,"initialDelaySeconds":5,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":1},"resources":{},"securityContext":{"capabilities":{"add":["NET_BIND_SERVICE","IPC_LOCK","IPC_OWNER","DAC_OVERRIDE","FOWNER","FSETID","SETGID","SETUID","NET_BIND_SERVICE","NET_RAW","AUDIT_WRITE"],"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":true,"runAsUser":1001},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/space","name":"ops-openldap-pvc"},{"mountPath":"/home/openldap/slapd.conf-replace","name":"ops-ldap-proxy-slapd-replace","subPath":"slapd.conf-replace"}]}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"noi-registry-secret"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":2001},"serviceAccount":"noi-service-account","serviceAccountName":"noi-service-account","terminationGracePeriodSeconds":10,"volumes":[{"configMap":{"defaultMode":420,"items":[{"key":"ldap-proxy-slapd-replace","path":"slapd.conf-replace"}],"name":"ops-ldap-proxy-config"},"name":"ops-ldap-proxy-slapd-replace"},{"name":"ops-openldap-pvc","persistentVolumeClaim":{"claimName":"ops-openldap-pvc"}}]}},"updateStrategy":{"type":"OnDelete"}},"status":{"collisionCount":0,"currentRevision":"ops-openldap-6dd6f9c459","observedGeneration":183,"readyReplicas":1,"replicas":1,"updateRevision":"ops-openldap-6dc7c7bc9d","updatedReplicas":1}}
  creationTimestamp: 2019-12-04T06:33:55Z
  generation: 184
  labels:
    app.kubernetes.io/instance: ops
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: openldap
    helm.sh/chart: openldap
    release: ops
  name: ops-openldap
  namespace: noi16
  resourceVersion: "12012922"
  selfLink: /apis/apps/v1/namespaces/noi16/statefulsets/ops-openldap
  uid: 0b952691-1660-11ea-bc6c-0016ac102868
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: ops
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: openldap
      helm.sh/chart: openldap
      release: ops
  serviceName: ops-ldapservice
  template:
    metadata:
      annotations:
        productID: 4DBA2B5A269740CAAE5FECDAFE0568AA
        productName: IBM Netcool Operations Insight v1.6.0.1 on IBM Cloud private
        productVersion: 1.6.0.1
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ops
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/name: openldap
        helm.sh/chart: openldap
        release: ops
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - command:
        - sh
        - -c
        - |
          curl -H "Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN" -H 'Accept: application/vnd.github.v3.raw' \
               -O -kL $GIT_MASTER_PREFIX/openldap/custom_sso.ldif
          curl -H "Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN" -H 'Accept: application/vnd.github.v3.raw' \
               -O -kL $GIT_MASTER_PREFIX/openldap/custom_start_server
          curl -H "Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN" -H 'Accept: application/vnd.github.v3.raw' \
               -O -kL $GIT_MASTER_PREFIX/openldap/custom_slapd.conf
          curl -H "Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN" -H 'Accept: application/vnd.github.v3.raw' \
               -O -kL $GIT_MASTER_PREFIX/openldap/openldap-servers-2.4.44-21.el7_6.x86_64.rpm
          curl -H "Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN" -H 'Accept: application/vnd.github.v3.raw' \
               -O -kL $GIT_MASTER_PREFIX/openldap/systemd-sysv-219-67.el7_7.1.x86_64.rpm
          curl -H "Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN" -H 'Accept: application/vnd.github.v3.raw' \
               -O -kL $GIT_MASTER_PREFIX/openldap/tcp_wrappers-libs-7.6-77.el7.x86_64.rpm
          curl -H "Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN" -H 'Accept: application/vnd.github.v3.raw' \
               -O -kL $GIT_MASTER_PREFIX/openldap/systemd-219-67.el7_7.1.x86_64.rpm
          curl -H "Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN" -H 'Accept: application/vnd.github.v3.raw' \
               -O -kL $GIT_MASTER_PREFIX/openldap/systemd-libs-219-67.el7_7.1.x86_64.rpm
          sudo yum install -y systemd-sysv-219-67.el7_7.1.x86_64.rpm tcp_wrappers-libs-7.6-77.el7.x86_64.rpm
          sudo yum install -y openldap-servers-2.4.44-21.el7_6.x86_64.rpm
          sudo curl -H "Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN" -H 'Accept: application/vnd.github.v3.raw' \
               -O -kL $GIT_MASTER_PREFIX/openldap/openldaplib.tgz
          sudo tar xzvf openldaplib.tgz -C /usr/local/lib --no-same-owner
          chmod a+x custom_start_server
          /home/openldap/custom_start_server
          #/home/openldap/start_server
          #while true; do sleep 100; done
        env:
        - name: GIT_MASTER_PREFIX
          valueFrom:
            configMapKeyRef:
              key: openldapgit-master-prefix
              name: ops-openldapgit-config
        - name: LICENSE
          value: accept
        - name: LDAP_URL
          value: ldap://localhost:389
        - name: LDAP_SUFFIX
          value: dc=mycluster,dc=icp
        - name: LDAP_BIND_DN
          value: cn=admin,dc=mycluster,dc=icp
        - name: GIT_PROJECT_OPENLDAP_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: GIT_PROJECT_OPENLDAP_AUTH_TOKEN
              name: ops-openldap-git-secret
              optional: false
        - name: LDAP_BIND_PWD
          valueFrom:
            secretKeyRef:
              key: LDAP_BIND_PASSWORD
              name: ops-ldap-secret
              optional: false
        - name: UNITY_ADMIN_PWD
          valueFrom:
            secretKeyRef:
              key: UNITY_ADMIN_PASSWORD
              name: ops-la-secret
              optional: false
        - name: ICP_ADMIN_PWD
          valueFrom:
            secretKeyRef:
              key: ICP_ADMIN_PASSWORD
              name: ops-icpadmin-secret
              optional: false
        - name: IMPACT_ADMIN_PWD
          valueFrom:
            secretKeyRef:
              key: IMPACT_ADMIN_PASSWORD
              name: ops-impact-secret
              optional: false
        - name: OMNIBUS_ROOT_PWD
          valueFrom:
            secretKeyRef:
              key: OMNIBUS_ROOT_PASSWORD
              name: ops-omni-secret
              optional: false
        image: mycluster.icp:8500/noi16/netcool-ldap-proxy-ee:1.6.0.1-99
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /usr/local/bin/ldapsearch
            - -x
            - -h
            - localhost
            - -LLL
            - -s
            - base
            - -b
            - ""
            - supportedSASLMechanisms
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        name: openldap
        ports:
        - containerPort: 389
          protocol: TCP
        - containerPort: 636
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/local/bin/ldapsearch
            - -x
            - -h
            - localhost
            - -LLL
            - -s
            - base
            - -b
            - ""
            - supportedSASLMechanisms
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            - IPC_LOCK
            - IPC_OWNER
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - SETGID
            - SETUID
            - NET_BIND_SERVICE
            - NET_RAW
            - AUDIT_WRITE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /space
          name: ops-openldap-pvc
        - mountPath: /home/openldap/slapd.conf-replace
          name: ops-ldap-proxy-slapd-replace
          subPath: slapd.conf-replace
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: noi-registry-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2001
      serviceAccount: noi-service-account
      serviceAccountName: noi-service-account
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: ldap-proxy-slapd-replace
            path: slapd.conf-replace
          name: ops-ldap-proxy-config
        name: ops-ldap-proxy-slapd-replace
      - name: ops-openldap-pvc
        persistentVolumeClaim:
          claimName: ops-openldap-pvc
  updateStrategy:
    type: OnDelete
status:
  collisionCount: 0
  currentRevision: ops-openldap-6dd6f9c459
  observedGeneration: 184
  readyReplicas: 1
  replicas: 1
  updateRevision: ops-openldap-74bb7f974
  updatedReplicas: 1
