apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"creationTimestamp":"2019-12-04T06:33:50Z","generation":20,"labels":{"app.kubernetes.io/instance":"ops","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"impactgui","helm.sh/chart":"impactgui","release":"ops"},"name":"ops-impactgui","namespace":"noi16","resourceVersion":"11574921","selfLink":"/apis/apps/v1/namespaces/noi16/statefulsets/ops-impactgui","uid":"087bb858-1660-11ea-bc6c-0016ac102868"},"spec":{"podManagementPolicy":"OrderedReady","replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/instance":"ops","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"impactgui","helm.sh/chart":"impactgui","release":"ops"}},"serviceName":"ops-impactgui","template":{"metadata":{"annotations":{"productID":"4DBA2B5A269740CAAE5FECDAFE0568AA","productName":"IBM Netcool Operations Insight v1.6.0.1 on IBM Cloud private","productVersion":"1.6.0.1"},"creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"ops","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"impactgui","helm.sh/chart":"impactgui","release":"ops"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64"]}]}]}}},"containers":[{"command":["sh","-c","curl -H \"Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN\" -H 'Accept: application/vnd.github.v3.raw' \\\n     -kL $GIT_MASTER_PREFIX/impactgui/start_server \\\n     -o /home/netcool/start_server\nchmod a+x start_server\n/home/netcool/start_server\n#while true; do sleep 100; done\n"],"env":[{"name":"GIT_PROJECT_OPENLDAP_AUTH_TOKEN","valueFrom":{"secretKeyRef":{"key":"GIT_PROJECT_OPENLDAP_AUTH_TOKEN","name":"ops-openldap-git-secret","optional":false}}},{"name":"GIT_MASTER_PREFIX","valueFrom":{"configMapKeyRef":{"key":"openldapgit-master-prefix","name":"ops-openldapgit-config"}}},{"name":"NCISERVERS_REPLICA_COUNT","value":"1"},{"name":"LICENSE","value":"accept"},{"name":"EXTERNAL_HOSTNAME","value":"impact.ops.mycluster.icp"},{"name":"IMPACT_GUI_SERVICE_NAME","value":"ops-impactgui"},{"name":"IMPACT_SERVERS_DOMAIN_NAME","value":"ops-nciservers"},{"name":"IMPACT_SERVER_BASE_HOSTNAME","value":"ops-nciserver"},{"name":"IMPACT_SERVERS_NAMESERVER_PORT","value":"9080"},{"name":"LDAP_SERVICE_NAME","value":"ops-ldapservice"},{"name":"LDAP_SERVICE_PORT","value":"389"},{"name":"LDAP_BIND_DN","value":"cn=admin,dc=mycluster,dc=icp"},{"name":"LDAP_BASE_DN","value":"dc=mycluster,dc=icp"},{"name":"LDAP_BIND_PWD","valueFrom":{"secretKeyRef":{"key":"LDAP_BIND_PASSWORD","name":"ops-ldap-secret","optional":false}}},{"name":"IMPACT_ADMIN_PASSWORD","valueFrom":{"secretKeyRef":{"key":"IMPACT_ADMIN_PASSWORD","name":"ops-impact-secret","optional":false}}},{"name":"SSO_DOMAIN","value":"ops.mycluster.icp"},{"name":"LTPA_KEY_FILE","value":"dash_ltpa.key"},{"name":"LDAP_VERIFY_PASSWORDS","value":"true"},{"name":"HELM_RELEASE","value":"ops"}],"image":"mycluster.icp:8500/noi16/netcool-impactgui-ee:1.6.0.1-99","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":40,"httpGet":{"path":"/ibm/console","port":17311,"scheme":"HTTPS"},"initialDelaySeconds":300,"periodSeconds":60,"successThreshold":1,"timeoutSeconds":10},"name":"impactgui","ports":[{"containerPort":17311,"protocol":"TCP"},{"containerPort":17310,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":250,"httpGet":{"path":"/ibm/console","port":17311,"scheme":"HTTPS"},"initialDelaySeconds":30,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"resources":{},"securityContext":{"capabilities":{"add":["DAC_OVERRIDE","FOWNER","FSETID","SETGID","SETUID","NET_BIND_SERVICE","NET_RAW","AUDIT_WRITE"],"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":true,"runAsUser":1001},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/space","name":"ops-impactgui-pvc"},{"mountPath":"/share","name":"ops-share-mount"},{"mountPath":"/space/impactgui.log4j.properties-update","name":"ops-impactgui-log4j-props","subPath":"impactgui.log4j.properties-update"},{"mountPath":"/space/server.props-update","name":"ops-impactgui-server-props","subPath":"server.props-update"}]},{"env":[{"name":"ICP_NOI_SHARED_SYNCFROM_SERVERS","valueFrom":{"configMapKeyRef":{"key":"impactgui","name":"ops-configuration-share"}}}],"image":"mycluster.icp:8500/noi16/netcool-configuration-share-ee:1.6.0.1-99","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":40,"httpGet":{"path":"/","port":8000,"scheme":"HTTP"},"initialDelaySeconds":300,"periodSeconds":60,"successThreshold":1,"timeoutSeconds":1},"name":"configuration-share","ports":[{"containerPort":8000,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":250,"httpGet":{"path":"/","port":8000,"scheme":"HTTP"},"initialDelaySeconds":30,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"50m","memory":"512Mi"}},"securityContext":{"capabilities":{"add":["NET_BIND_SERVICE"],"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":true,"runAsUser":1001},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/share","name":"ops-share-mount"}]}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"noi-registry-secret"}],"initContainers":[{"env":[{"name":"ICP_NOI_SHARED_SYNCFROM_SERVERS","valueFrom":{"configMapKeyRef":{"key":"impactgui","name":"ops-configuration-share"}}},{"name":"ICP_NOI_SHARED_EXIT_WHEN_FOUND","value":"True"}],"image":"mycluster.icp:8500/noi16/netcool-configuration-share-ee:1.6.0.1-99","imagePullPolicy":"Always","name":"wait4db2ese","resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"50m","memory":"512Mi"}},"securityContext":{"capabilities":{"add":["NET_BIND_SERVICE"],"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":true,"runAsUser":1001},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/share","name":"ops-share-mount"}]}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":2001,"runAsNonRoot":true,"runAsUser":1001},"serviceAccount":"noi-service-account","serviceAccountName":"noi-service-account","terminationGracePeriodSeconds":30,"volumes":[{"name":"ops-impactgui-pvc","persistentVolumeClaim":{"claimName":"ops-impactgui-pvc"}},{"emptyDir":{},"name":"ops-share-mount"},{"configMap":{"defaultMode":420,"items":[{"key":"impactgui-log4j-props-update","path":"impactgui.log4j.properties-update"}],"name":"ops-impactgui-config"},"name":"ops-impactgui-log4j-props"},{"configMap":{"defaultMode":420,"items":[{"key":"server-props-update","path":"server.props-update"}],"name":"ops-impactgui-config"},"name":"ops-impactgui-server-props"}]}},"updateStrategy":{"type":"OnDelete"}},"status":{"collisionCount":0,"currentRevision":"ops-impactgui-546cc5b5c4","observedGeneration":20,"readyReplicas":1,"replicas":1,"updateRevision":"ops-impactgui-66bbfbb584"}}
  creationTimestamp: 2019-12-04T06:33:50Z
  generation: 21
  labels:
    app.kubernetes.io/instance: ops
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: impactgui
    helm.sh/chart: impactgui
    release: ops
  name: ops-impactgui
  namespace: noi16
  resourceVersion: "12396090"
  selfLink: /apis/apps/v1/namespaces/noi16/statefulsets/ops-impactgui
  uid: 087bb858-1660-11ea-bc6c-0016ac102868
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: ops
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: impactgui
      helm.sh/chart: impactgui
      release: ops
  serviceName: ops-impactgui
  template:
    metadata:
      annotations:
        productID: 4DBA2B5A269740CAAE5FECDAFE0568AA
        productName: IBM Netcool Operations Insight v1.6.0.1 on IBM Cloud private
        productVersion: 1.6.0.1
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ops
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/name: impactgui
        helm.sh/chart: impactgui
        release: ops
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - command:
        - sh
        - -c
        - |
          cp start_server start_server.original
          curl -H "Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN" -H 'Accept: application/vnd.github.v3.raw' \
               -kL $GIT_MASTER_PREFIX/impactgui/start_server \
               -o /home/netcool/start_server
          chmod a+x start_server
          /home/netcool/start_server
          #while true; do sleep 100; done
        env:
        - name: GIT_PROJECT_OPENLDAP_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: GIT_PROJECT_OPENLDAP_AUTH_TOKEN
              name: ops-openldap-git-secret
              optional: false
        - name: GIT_MASTER_PREFIX
          valueFrom:
            configMapKeyRef:
              key: openldapgit-master-prefix
              name: ops-openldapgit-config
        - name: NCISERVERS_REPLICA_COUNT
          value: "1"
        - name: LICENSE
          value: accept
        - name: EXTERNAL_HOSTNAME
          value: impact.ops.mycluster.icp
        - name: IMPACT_GUI_SERVICE_NAME
          value: ops-impactgui
        - name: IMPACT_SERVERS_DOMAIN_NAME
          value: ops-nciservers
        - name: IMPACT_SERVER_BASE_HOSTNAME
          value: ops-nciserver
        - name: IMPACT_SERVERS_NAMESERVER_PORT
          value: "9080"
        - name: LDAP_SERVICE_NAME
          value: ops-ldapservice
        - name: LDAP_SERVICE_PORT
          value: "389"
        - name: LDAP_BIND_DN
          value: cn=admin,dc=mycluster,dc=icp
        - name: LDAP_BASE_DN
          value: dc=mycluster,dc=icp
        - name: LDAP_BIND_PWD
          valueFrom:
            secretKeyRef:
              key: LDAP_BIND_PASSWORD
              name: ops-ldap-secret
              optional: false
        - name: IMPACT_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: IMPACT_ADMIN_PASSWORD
              name: ops-impact-secret
              optional: false
        - name: SSO_DOMAIN
          value: ops.mycluster.icp
        - name: LTPA_KEY_FILE
          value: dash_ltpa.key
        - name: LDAP_VERIFY_PASSWORDS
          value: "true"
        - name: HELM_RELEASE
          value: ops
        image: mycluster.icp:8500/noi16/netcool-impactgui-ee:1.6.0.1-99
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 40
          httpGet:
            path: /ibm/console
            port: 17311
            scheme: HTTPS
          initialDelaySeconds: 300
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        name: impactgui
        ports:
        - containerPort: 17311
          protocol: TCP
        - containerPort: 17310
          protocol: TCP
        readinessProbe:
          failureThreshold: 250
          httpGet:
            path: /ibm/console
            port: 17311
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources: {}
        securityContext:
          capabilities:
            add:
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - SETGID
            - SETUID
            - NET_BIND_SERVICE
            - NET_RAW
            - AUDIT_WRITE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /space
          name: ops-impactgui-pvc
        - mountPath: /share
          name: ops-share-mount
        - mountPath: /space/impactgui.log4j.properties-update
          name: ops-impactgui-log4j-props
          subPath: impactgui.log4j.properties-update
        - mountPath: /space/server.props-update
          name: ops-impactgui-server-props
          subPath: server.props-update
      - env:
        - name: ICP_NOI_SHARED_SYNCFROM_SERVERS
          valueFrom:
            configMapKeyRef:
              key: impactgui
              name: ops-configuration-share
        image: mycluster.icp:8500/noi16/netcool-configuration-share-ee:1.6.0.1-99
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 40
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        name: configuration-share
        ports:
        - containerPort: 8000
          protocol: TCP
        readinessProbe:
          failureThreshold: 250
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 512Mi
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /share
          name: ops-share-mount
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: noi-registry-secret
      initContainers:
      - env:
        - name: ICP_NOI_SHARED_SYNCFROM_SERVERS
          valueFrom:
            configMapKeyRef:
              key: impactgui
              name: ops-configuration-share
        - name: ICP_NOI_SHARED_EXIT_WHEN_FOUND
          value: "True"
        image: mycluster.icp:8500/noi16/netcool-configuration-share-ee:1.6.0.1-99
        imagePullPolicy: Always
        name: wait4db2ese
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 512Mi
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /share
          name: ops-share-mount
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2001
        runAsNonRoot: true
        runAsUser: 1001
      serviceAccount: noi-service-account
      serviceAccountName: noi-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ops-impactgui-pvc
        persistentVolumeClaim:
          claimName: ops-impactgui-pvc
      - emptyDir: {}
        name: ops-share-mount
      - configMap:
          defaultMode: 420
          items:
          - key: impactgui-log4j-props-update
            path: impactgui.log4j.properties-update
          name: ops-impactgui-config
        name: ops-impactgui-log4j-props
      - configMap:
          defaultMode: 420
          items:
          - key: server-props-update
            path: server.props-update
          name: ops-impactgui-config
        name: ops-impactgui-server-props
  updateStrategy:
    type: OnDelete
status:
  collisionCount: 0
  currentRevision: ops-impactgui-546cc5b5c4
  observedGeneration: 21
  readyReplicas: 1
  replicas: 1
  updateRevision: ops-impactgui-cbf7d7777
  updatedReplicas: 1
