apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"creationTimestamp":"2019-12-04T06:33:51Z","generation":21,"labels":{"app.kubernetes.io/instance":"ops","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"nciserver","helm.sh/chart":"nciserver","release":"ops"},"name":"ops-nciserver","namespace":"noi16","resourceVersion":"11542481","selfLink":"/apis/apps/v1/namespaces/noi16/statefulsets/ops-nciserver","uid":"096fd521-1660-11ea-bc6c-0016ac102868"},"spec":{"podManagementPolicy":"OrderedReady","replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app.kubernetes.io/instance":"ops","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"nciserver","helm.sh/chart":"nciserver","release":"ops"}},"serviceName":"ops-nciservers","template":{"metadata":{"annotations":{"productID":"4DBA2B5A269740CAAE5FECDAFE0568AA","productName":"IBM Netcool Operations Insight v1.6.0.1 on IBM Cloud private","productVersion":"1.6.0.1"},"creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"ops","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"nciserver","appClass":"impactcore","helm.sh/chart":"nciserver","name":"impact","release":"ops"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"beta.kubernetes.io/arch","operator":"In","values":["amd64"]}]}]}}},"containers":[{"command":["sh","-c","curl -H \"Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN\" -H 'Accept: application/vnd.github.v3.raw' \\\n     -kL $GIT_MASTER_PREFIX/nciserver/start_server \\\n     -o /home/netcool/start_server\nchmod a+x start_server\n/home/netcool/start_server\n#while true; do sleep 100; done\n"],"env":[{"name":"GIT_PROJECT_OPENLDAP_AUTH_TOKEN","valueFrom":{"secretKeyRef":{"key":"GIT_PROJECT_OPENLDAP_AUTH_TOKEN","name":"ops-openldap-git-secret","optional":false}}},{"name":"GIT_MASTER_PREFIX","valueFrom":{"configMapKeyRef":{"key":"openldapgit-master-prefix","name":"ops-openldapgit-config"}}},{"name":"NCISERVERS_REPLICA_COUNT","value":"1"},{"name":"LICENSE","value":"accept"},{"name":"OBJSERVER_SERVICE_NAME","value":"ops-objserv-agg-primary"},{"name":"OBJSERVER_BK_SERVICE_NAME","value":"ops-objserv-agg-backup"},{"name":"OBJSERVER_BK_SERVICE_PORT","value":"4100"},{"name":"OMNIBUS_ROOT_PWD","valueFrom":{"secretKeyRef":{"key":"OMNIBUS_ROOT_PASSWORD","name":"ops-omni-secret","optional":false}}},{"name":"DB_SERVICE_NAME","value":"ops-db2ese-service"},{"name":"NCI_SET_PRIMARY","value":"false"},{"name":"IMPACT_NAMESERVER_PORT","value":"9080"},{"name":"IMPACTGUI_HTTP_SERVICE","value":"ops-impactgui"},{"name":"LDAP_SERVICE_NAME","value":"ops-ldapservice"},{"name":"LDAP_SERVICE_PORT","value":"389"},{"name":"LDAP_BIND_DN","value":"cn=admin,dc=mycluster,dc=icp"},{"name":"LDAP_BASE_DN","value":"dc=mycluster,dc=icp"},{"name":"LDAP_BIND_PWD","valueFrom":{"secretKeyRef":{"key":"LDAP_BIND_PASSWORD","name":"ops-ldap-secret","optional":false}}},{"name":"IMPACT_ADMIN_PASSWORD","valueFrom":{"secretKeyRef":{"key":"IMPACT_ADMIN_PASSWORD","name":"ops-impact-secret","optional":false}}},{"name":"SSO_DOMAIN","value":"ops.mycluster.icp"},{"name":"LTPA_KEY_FILE","value":"dash_ltpa.key"},{"name":"LDAP_VERIFY_PASSWORDS","value":"true"},{"name":"HELM_RELEASE","value":"ops"}],"image":"mycluster.icp:8500/noi16/netcool-nciserver-ee:1.6.0.1-110","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":40,"initialDelaySeconds":300,"periodSeconds":60,"successThreshold":1,"tcpSocket":{"port":9080},"timeoutSeconds":10},"name":"nciserver","ports":[{"containerPort":9080,"protocol":"TCP"},{"containerPort":1527,"protocol":"TCP"},{"containerPort":2000,"protocol":"TCP"},{"containerPort":3000,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":250,"initialDelaySeconds":30,"periodSeconds":10,"successThreshold":1,"tcpSocket":{"port":9080},"timeoutSeconds":5},"resources":{},"securityContext":{"capabilities":{"add":["DAC_OVERRIDE","NET_BIND_SERVICE","NET_RAW"],"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":true,"runAsUser":1001},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/space","name":"space"},{"mountPath":"/share","name":"ops-share-mount"},{"mountPath":"/space/impactserver.log4j.properties-update","name":"ops-nciserver-log4j-props","subPath":"impactserver.log4j.properties-update"},{"mountPath":"/space/NCI_server.props-update","name":"ops-nciserver-server-props","subPath":"NCI_server.props-update"},{"mountPath":"/space/jvm.options-replace","name":"ops-nciserver-jvm-options","subPath":"jvm.options-replace"},{"mountPath":"/space/derby-extensions.sql","name":"ops-nciserver-derby-extensions-sql","subPath":"derby-extensions.sql"}]},{"env":[{"name":"LICENSE","value":"accept"}],"image":"mycluster.icp:8500/noi16/netcool-configuration-share-ee:1.6.0.1-99","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":40,"httpGet":{"path":"/","port":8000,"scheme":"HTTP"},"initialDelaySeconds":300,"periodSeconds":60,"successThreshold":1,"timeoutSeconds":10},"name":"configuration-share","ports":[{"containerPort":8000,"protocol":"TCP"}],"readinessProbe":{"failureThreshold":250,"httpGet":{"path":"/","port":8000,"scheme":"HTTP"},"initialDelaySeconds":30,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"50m","memory":"512Mi"}},"securityContext":{"capabilities":{"add":["NET_BIND_SERVICE"],"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":true,"runAsUser":1001},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/share","name":"ops-share-mount"}]}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"noi-registry-secret"}],"initContainers":[{"env":[{"name":"ICP_NOI_SHARED_SYNCFROM_SERVERS","value":"[{\"server\": \"http://ops-webgui:8000/\" , \"files\" : [{ \"file\": \"keys/dash_ltpa.key\"}]}]"},{"name":"ICP_NOI_SHARED_EXIT_WHEN_FOUND","value":"True"}],"image":"mycluster.icp:8500/noi16/netcool-configuration-share-ee:1.6.0.1-99","imagePullPolicy":"Always","name":"wait4db2ese","resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"50m","memory":"512Mi"}},"securityContext":{"capabilities":{"add":["NET_BIND_SERVICE"],"drop":["ALL"]},"privileged":false,"readOnlyRootFilesystem":false,"runAsNonRoot":true,"runAsUser":1001},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/share","name":"ops-share-mount"}]}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{"fsGroup":2001,"runAsNonRoot":true,"runAsUser":1001},"serviceAccount":"noi-service-account","serviceAccountName":"noi-service-account","terminationGracePeriodSeconds":30,"volumes":[{"emptyDir":{},"name":"ops-share-mount"},{"configMap":{"defaultMode":420,"items":[{"key":"impactcore-log4j-props-update","path":"impactserver.log4j.properties-update"}],"name":"ops-nciserver-config"},"name":"ops-nciserver-log4j-props"},{"configMap":{"defaultMode":420,"items":[{"key":"impactcore-server-props-update","path":"NCI_server.props-update"}],"name":"ops-nciserver-config"},"name":"ops-nciserver-server-props"},{"configMap":{"defaultMode":420,"items":[{"key":"impactcore-jvm-options-replace","path":"jvm.options-replace"}],"name":"ops-nciserver-config"},"name":"ops-nciserver-jvm-options"},{"configMap":{"defaultMode":420,"items":[{"key":"impactcore-derby-sql-extensions","path":"derby-extensions.sql"}],"name":"ops-nciserver-config"},"name":"ops-nciserver-derby-extensions-sql"}]}},"updateStrategy":{"type":"OnDelete"},"volumeClaimTemplates":[{"metadata":{"creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"ops","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"nciserver","helm.sh/chart":"nciserver","release":"ops"},"name":"space"},"spec":{"accessModes":["ReadWriteOnce"],"dataSource":null,"resources":{"requests":{"storage":"5Gi"}},"storageClassName":"gluster-storage-nciserver","volumeMode":"Filesystem"},"status":{"phase":"Pending"}}]},"status":{"collisionCount":0,"currentRevision":"ops-nciserver-68546c6d","observedGeneration":21,"readyReplicas":1,"replicas":1,"updateRevision":"ops-nciserver-76c4585499"}}
  creationTimestamp: 2019-12-04T06:33:51Z
  generation: 22
  labels:
    app.kubernetes.io/instance: ops
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: nciserver
    helm.sh/chart: nciserver
    release: ops
  name: ops-nciserver
  namespace: noi16
  resourceVersion: "11575775"
  selfLink: /apis/apps/v1/namespaces/noi16/statefulsets/ops-nciserver
  uid: 096fd521-1660-11ea-bc6c-0016ac102868
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: ops
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: nciserver
      helm.sh/chart: nciserver
      release: ops
  serviceName: ops-nciservers
  template:
    metadata:
      annotations:
        productID: 4DBA2B5A269740CAAE5FECDAFE0568AA
        productName: IBM Netcool Operations Insight v1.6.0.1 on IBM Cloud private
        productVersion: 1.6.0.1
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ops
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/name: nciserver
        appClass: impactcore
        helm.sh/chart: nciserver
        name: impact
        release: ops
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - command:
        - sh
        - -c
        - |
          cp start_server start_server.original
          curl -H "Authorization: token $GIT_PROJECT_OPENLDAP_AUTH_TOKEN" -H 'Accept: application/vnd.github.v3.raw' \
               -kL $GIT_MASTER_PREFIX/nciserver/start_server \
               -o /home/netcool/start_server
          chmod a+x start_server
          /home/netcool/start_server
          #while true; do sleep 100; done
        env:
        - name: GIT_PROJECT_OPENLDAP_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: GIT_PROJECT_OPENLDAP_AUTH_TOKEN
              name: ops-openldap-git-secret
              optional: false
        - name: GIT_MASTER_PREFIX
          valueFrom:
            configMapKeyRef:
              key: openldapgit-master-prefix
              name: ops-openldapgit-config
        - name: NCISERVERS_REPLICA_COUNT
          value: "1"
        - name: LICENSE
          value: accept
        - name: OBJSERVER_SERVICE_NAME
          value: ops-objserv-agg-primary
        - name: OBJSERVER_BK_SERVICE_NAME
          value: ops-objserv-agg-backup
        - name: OBJSERVER_BK_SERVICE_PORT
          value: "4100"
        - name: OMNIBUS_ROOT_PWD
          valueFrom:
            secretKeyRef:
              key: OMNIBUS_ROOT_PASSWORD
              name: ops-omni-secret
              optional: false
        - name: DB_SERVICE_NAME
          value: ops-db2ese-service
        - name: NCI_SET_PRIMARY
          value: "false"
        - name: IMPACT_NAMESERVER_PORT
          value: "9080"
        - name: IMPACTGUI_HTTP_SERVICE
          value: ops-impactgui
        - name: LDAP_SERVICE_NAME
          value: ops-ldapservice
        - name: LDAP_SERVICE_PORT
          value: "389"
        - name: LDAP_BIND_DN
          value: cn=admin,dc=mycluster,dc=icp
        - name: LDAP_BASE_DN
          value: dc=mycluster,dc=icp
        - name: LDAP_BIND_PWD
          valueFrom:
            secretKeyRef:
              key: LDAP_BIND_PASSWORD
              name: ops-ldap-secret
              optional: false
        - name: IMPACT_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: IMPACT_ADMIN_PASSWORD
              name: ops-impact-secret
              optional: false
        - name: SSO_DOMAIN
          value: ops.mycluster.icp
        - name: LTPA_KEY_FILE
          value: dash_ltpa.key
        - name: LDAP_VERIFY_PASSWORDS
          value: "true"
        - name: HELM_RELEASE
          value: ops
        image: mycluster.icp:8500/noi16/netcool-nciserver-ee:1.6.0.1-110
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 40
          initialDelaySeconds: 300
          periodSeconds: 60
          successThreshold: 1
          tcpSocket:
            port: 9080
          timeoutSeconds: 10
        name: nciserver
        ports:
        - containerPort: 9080
          protocol: TCP
        - containerPort: 1527
          protocol: TCP
        - containerPort: 2000
          protocol: TCP
        - containerPort: 3000
          protocol: TCP
        readinessProbe:
          failureThreshold: 250
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9080
          timeoutSeconds: 5
        resources: {}
        securityContext:
          capabilities:
            add:
            - DAC_OVERRIDE
            - NET_BIND_SERVICE
            - NET_RAW
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /space
          name: space
        - mountPath: /share
          name: ops-share-mount
        - mountPath: /space/impactserver.log4j.properties-update
          name: ops-nciserver-log4j-props
          subPath: impactserver.log4j.properties-update
        - mountPath: /space/NCI_server.props-update
          name: ops-nciserver-server-props
          subPath: NCI_server.props-update
        - mountPath: /space/jvm.options-replace
          name: ops-nciserver-jvm-options
          subPath: jvm.options-replace
        - mountPath: /space/derby-extensions.sql
          name: ops-nciserver-derby-extensions-sql
          subPath: derby-extensions.sql
      - env:
        - name: LICENSE
          value: accept
        image: mycluster.icp:8500/noi16/netcool-configuration-share-ee:1.6.0.1-99
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 40
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        name: configuration-share
        ports:
        - containerPort: 8000
          protocol: TCP
        readinessProbe:
          failureThreshold: 250
          httpGet:
            path: /
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 512Mi
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /share
          name: ops-share-mount
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: noi-registry-secret
      initContainers:
      - env:
        - name: ICP_NOI_SHARED_SYNCFROM_SERVERS
          value: '[{"server": "http://ops-webgui:8000/" , "files" : [{ "file": "keys/dash_ltpa.key"}]}]'
        - name: ICP_NOI_SHARED_EXIT_WHEN_FOUND
          value: "True"
        image: mycluster.icp:8500/noi16/netcool-configuration-share-ee:1.6.0.1-99
        imagePullPolicy: Always
        name: wait4db2ese
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 512Mi
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /share
          name: ops-share-mount
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2001
        runAsNonRoot: true
        runAsUser: 1001
      serviceAccount: noi-service-account
      serviceAccountName: noi-service-account
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: ops-share-mount
      - configMap:
          defaultMode: 420
          items:
          - key: impactcore-log4j-props-update
            path: impactserver.log4j.properties-update
          name: ops-nciserver-config
        name: ops-nciserver-log4j-props
      - configMap:
          defaultMode: 420
          items:
          - key: impactcore-server-props-update
            path: NCI_server.props-update
          name: ops-nciserver-config
        name: ops-nciserver-server-props
      - configMap:
          defaultMode: 420
          items:
          - key: impactcore-jvm-options-replace
            path: jvm.options-replace
          name: ops-nciserver-config
        name: ops-nciserver-jvm-options
      - configMap:
          defaultMode: 420
          items:
          - key: impactcore-derby-sql-extensions
            path: derby-extensions.sql
          name: ops-nciserver-config
        name: ops-nciserver-derby-extensions-sql
  updateStrategy:
    type: OnDelete
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: ops
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/name: nciserver
        helm.sh/chart: nciserver
        release: ops
      name: space
    spec:
      accessModes:
      - ReadWriteOnce
      dataSource: null
      resources:
        requests:
          storage: 5Gi
      storageClassName: gluster-storage-nciserver
      volumeMode: Filesystem
    status:
      phase: Pending
status:
  collisionCount: 0
  currentRevision: ops-nciserver-68546c6d
  observedGeneration: 22
  readyReplicas: 1
  replicas: 1
  updateRevision: ops-nciserver-db87fc76b
